# -*- coding: utf-8 -*-
"""osoc1_core_uarch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1otlKaUe_eGQhf_8zPkZO124izZ0bxm5r

Assembler functions
"""

import re

def get_max(bits):
    """Dynamically calculates the maximum integer for a given physical wire width."""
    return (1 << bits) - 1

def verify_cpu_results(actual_file, expected_file):
    print(f"\n{'='*20} SPARSE REGRESSION CHECK {'='*20}")

    try:
        with open(actual_file, 'r') as f: actual_lines = f.readlines()
        with open(expected_file, 'r') as f: expected_lines = f.readlines()
    except FileNotFoundError as e:
        print(f"❌ Error: {e}")
        return False

    # 1. Create a Dictionary of ACTUAL values for easy lookup
    # key: "x01", value: the full line string
    actual_map = {}
    for line in actual_lines:
        match = re.search(r'(x\d{2})', line)
        if match:
            actual_map[match.group(1)] = line.strip()

    # 2. Iterate through EXPECTED file and only check what is present
    mismatches = 0
    checks_performed = 0

    for exp_line in expected_lines:
        exp_line = exp_line.strip()
        # Find if this line contains a register name (e.g., x01, x20)
        match = re.search(r'(x\d{2})', exp_line)

        if match:
            reg_name = match.group(1)
            checks_performed += 1

            if reg_name in actual_map:
                act_line = actual_map[reg_name]

                if act_line == exp_line:
                    print(f"✅ {reg_name}: Match! ({act_line.split(':')[-1].strip()})")
                else:
                    mismatches += 1
                    print(f"🚨 {reg_name} MISMATCH:")
                    print(f"   Expected: {exp_line}")
                    print(f"   Actual  : {act_line}")
            else:
                print(f"⚠️  Warning: {reg_name} found in expected file but not in actual dump.")

    # 3. Final Summary
    print(f"{'-'*53}")
    if checks_performed == 0:
        print("❓ No registers found in expected file to verify.")
        return False
    elif mismatches == 0:
        print(f"✨ SUCCESS: All {checks_performed} targeted registers verified!")
        return True
    else:
        print(f"⚠️  FAILURE: {mismatches} out of {checks_performed} checks failed.")
        return False

"""assembler"""

def mini_assembler(asm_line_i):
    """
    Robust RISC-V Assembler with ABI Support & Professional Boundary Checks.
    Supports: addi, lui, add, sub, sll, slt, sltu, xor, srl, sra, or, and, lb, lw, sb, sw
    """
    # 1. Standard RISC-V ABI Register Mapping
    ABI_MAP = {
        'zero': 0, 'ra': 1, 'sp': 2, 'gp': 3, 'tp': 4,
        't0': 5, 't1': 6, 't2': 7, 's0': 8, 'fp': 8, 's1': 9,
        'a0': 10, 'a1': 11, 'a2': 12, 'a3': 13, 'a4': 14, 'a5': 15, 'a6': 16, 'a7': 17,
        's2': 18, 's3': 19, 's4': 20, 's5': 21, 's6': 22, 's7': 23, 's8': 24, 's9': 25, 's10': 26, 's11': 27,
        't3': 28, 't4': 29, 't5': 30, 't6': 31
    }

    def parse_reg(reg_str):
        reg_str = reg_str.lower().strip().replace(',', '')
        if reg_str.startswith('x'):
            return int(reg_str[1:])
        if reg_str in ABI_MAP:
            return ABI_MAP[reg_str]
        raise ValueError(f"Unknown register: {reg_str}")

    def parse_imm(imm_str, bits, is_signed=True):
        """
        The Universal Gatekeeper: Handles decimals, hex bit-patterns, and strict bounds.
        """
        val = int(imm_str, 0)

        if is_signed:
            min_val = -(1 << (bits - 1))
            max_val = (1 << (bits - 1)) - 1

            # Professional Hex Fallback: Convert to signed equivalent (-1) if needed
            if imm_str.lower().startswith('0x') and 0 <= val <= ((1 << bits) - 1):
                if val > max_val:
                    val -= (1 << bits)
        else:
            min_val = 0
            max_val = (1 << bits) - 1

        # The Hardware Crash: Fail loudly if out of bounds
        if not (min_val <= val <= max_val):
            raise ValueError(f"HARDWARE FAULT: Immediate {imm_str} out of {bits}-bit range [{min_val} to {max_val}]")

        return val & ((1 << bits) - 1)

    # 2. Clean the line and Tokenize
    clean_line = asm_line_i.split('#')[0].replace(',', ' ')
    tokens = clean_line.split()

    if not tokens:
        return None

    instr = tokens[0].lower()

    try:
        # --- I-TYPE: ADDI (Opcode: 19) ---
        if instr == "addi":
            rd  = parse_reg(tokens[1])
            rs1 = parse_reg(tokens[2])
            imm_12b = parse_imm(tokens[3], 12, is_signed=True)
            return (imm_12b << 20) | (rs1 << 15) | (0 << 12) | (rd << 7) | 19

        # --- U-TYPE: LUI (Opcode: 55) ---
        elif instr == "lui":
            rd = parse_reg(tokens[1])
            imm_20b = parse_imm(tokens[2], 20, is_signed=False)
            return (imm_20b << 12) | (rd << 7) | 55

        # --- R-TYPE: ALL ALU OPERATIONS (Opcode: 51) ---
        elif instr in ["add", "sub", "sll", "slt", "sltu", "xor", "srl", "sra", "or", "and"]:
            rd  = parse_reg(tokens[1])
            rs1 = parse_reg(tokens[2])
            rs2 = parse_reg(tokens[3])

            # Professional Lookup Table for Hardware Routing (f3, f7)
            rtype_map = {
                "add":  (0, 0x00),
                "sub":  (0, 0x20),
                "sll":  (1, 0x00), # Shift Left Logical
                "slt":  (2, 0x00), # Set Less Than
                "sltu": (3, 0x00), # Set Less Than Unsigned
                "xor":  (4, 0x00), # Bitwise XOR
                "srl":  (5, 0x00), # Shift Right Logical
                "sra":  (5, 0x20), # Shift Right Arithmetic (Preserves Sign)
                "or":   (6, 0x00), # Bitwise OR
                "and":  (7, 0x00)  # Bitwise AND
            }

            f3, f7 = rtype_map[instr]
            return (f7 << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | 51

        # --- I-TYPE: LOADS (Opcode: 3) ---
        elif instr in ["lb", "lw"]:
            rd = parse_reg(tokens[1])
            mem_op = tokens[2].replace(')', '').split('(')
            imm_12b = parse_imm(mem_op[0], 12, is_signed=True)
            rs1 = parse_reg(mem_op[1])
            f3 = 0 if instr == "lb" else 2
            return (imm_12b << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | 3

        # --- S-TYPE: STORES (Opcode: 35) ---
        elif instr in ["sb", "sw"]:
            rs2 = parse_reg(tokens[1])
            mem_op = tokens[2].replace(')', '').split('(')
            imm_12b = parse_imm(mem_op[0], 12, is_signed=True)
            rs1 = parse_reg(mem_op[1])
            f3 = 0 if instr == "sb" else 2

            imm_11_5 = (imm_12b >> 5) & 0x7F
            imm_4_0  = imm_12b & 0x1F
            return (imm_11_5 << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (imm_4_0 << 7) | 35

       # --- I-TYPE: ALL ALU OPERATIONS (Opcode: 19) ---
        elif instr in ["addi", "slti", "sltiu", "xori", "ori", "andi", "slli", "srli", "srai"]:
            rd  = parse_reg(tokens[1])
            rs1 = parse_reg(tokens[2])
            imm_val = parse_imm(tokens[3], 12, is_signed=True)

            itype_map = {
                "addi":  (0, 0x00),
                "slli":  (1, 0x00),
                "slti":  (2, 0x00),
                "sltiu": (3, 0x00),
                "xori":  (4, 0x00),
                "srli":  (5, 0x00),
                "srai":  (5, 0x20), # 0x20 in the top 7 bits tells the hardware to preserve the sign
                "ori":   (6, 0x00),
                "andi":  (7, 0x00)
            }

            f3, f7_val = itype_map[instr]

            # Hardware Routing: If it's a shift, pack the f7 value into the top of the immediate
            if instr in ["slli", "srli", "srai"]:
                shamt = imm_val & 0x1F # Keep only the bottom 5 bits
                imm_12b = (f7_val << 5) | shamt
            else:
                imm_12b = imm_val & 0xFFF

            return (imm_12b << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | 19

            # --- I-TYPE: LOADS (Opcode: 3) ---
        elif instr in ["lb", "lh", "lw", "lbu", "lhu"]:
            rd = parse_reg(tokens[1])
            mem_op = tokens[2].replace(')', '').split('(')
            imm_12b = parse_imm(mem_op[0], 12, is_signed=True)
            rs1 = parse_reg(mem_op[1])

            # The Hardware f3 Routing Map
            load_f3_map = {
                "lb":  0, # 000
                "lh":  1, # 001
                "lw":  2, # 010
                "lbu": 4, # 100 (Unsigned Byte)
                "lhu": 5  # 101 (Unsigned Halfword)
            }
            f3 = load_f3_map[instr]
            return (imm_12b << 20) | (rs1 << 15) | (f3 << 12) | (rd << 7) | 3

        # --- S-TYPE: STORES (Opcode: 35) ---
        elif instr in ["sb", "sh", "sw"]:
            rs2 = parse_reg(tokens[1])
            mem_op = tokens[2].replace(')', '').split('(')
            imm_12b = parse_imm(mem_op[0], 12, is_signed=True)
            rs1 = parse_reg(mem_op[1])

            # The Hardware f3 Routing Map
            store_f3_map = {
                "sb": 0, # 000
                "sh": 1, # 001
                "sw": 2  # 010
            }
            f3 = store_f3_map[instr]

            # S-Type splits the 12-bit immediate: [11:5] and [4:0]
            imm_11_5 = (imm_12b >> 5) & 0x7F
            imm_4_0  = imm_12b & 0x1F
            return (imm_11_5 << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (imm_4_0 << 7) | 35
       # --- U-TYPE: AUIPC (Opcode: 23) ---
        # Boundary Check: 20-bit unsigned [0 to 1,048,575]
        elif instr == "auipc":
            rd = parse_reg(tokens[1])
            imm_20b = parse_imm(tokens[2], 20, is_signed=False)
            return (imm_20b << 12) | (rd << 7) | 23

        # --- J-TYPE: JAL (Opcode: 111) ---
        # Boundary Check: 21-bit signed [-1,048,576 to 1,048,574]
        elif instr == "jal":
            rd = parse_reg(tokens[1])
            imm_val = parse_imm(tokens[2], 21, is_signed=True)

            # J-Type Scramble: imm[20|10:1|11|19:12]
            imm_20    = (imm_val >> 20) & 0x1
            imm_19_12 = (imm_val >> 12) & 0xFF
            imm_11    = (imm_val >> 11) & 0x1
            imm_10_1  = (imm_val >> 1)  & 0x3FF
            return (imm_20 << 31) | (imm_10_1 << 21) | (imm_11 << 20) | (imm_19_12 << 12) | (rd << 7) | 111

        # --- I-TYPE: JALR (Opcode: 103) ---
        # Boundary Check: 12-bit signed [-2048 to 2047]
        elif instr == "jalr":
            rd = parse_reg(tokens[1])
            mem_op = tokens[2].replace(')', '').split('(')
            imm_12b = parse_imm(mem_op[0], 12, is_signed=True)
            rs1 = parse_reg(mem_op[1])
            return (imm_12b << 20) | (rs1 << 15) | (0 << 12) | (rd << 7) | 103

        # --- B-TYPE: BRANCHES (Opcode: 99) ---
        # Boundary Check: 13-bit signed [-4096 to 4094]
        elif instr in ["beq", "bne", "blt", "bge", "bltu", "bgeu"]:
            rs1 = parse_reg(tokens[1])
            rs2 = parse_reg(tokens[2])
            imm_val = parse_imm(tokens[3], 13, is_signed=True)

            branch_f3 = {"beq": 0, "bne": 1, "blt": 4, "bge": 5, "bltu": 6, "bgeu": 7}
            f3 = branch_f3[instr]

            # B-Type Scramble: imm[12|10:5|4:1|11]
            imm_12   = (imm_val >> 12) & 0x1
            imm_11   = (imm_val >> 11) & 0x1
            imm_10_5 = (imm_val >> 5)  & 0x3F
            imm_4_1  = (imm_val >> 1)  & 0xF
            return (imm_12 << 31) | (imm_10_5 << 25) | (rs2 << 20) | (rs1 << 15) | (f3 << 12) | (imm_4_1 << 8) | (imm_11 << 7) | 99


    except IndexError:
        print(f"Error parsing line: {asm_line_i} - Missing arguments!")
        return None

    print(f"Unsupported instruction: {instr}")
    return None

def debug_disassemble(op_o, rd_o, rs1_o, rs2_o, f3_o, f7_o, imm_o):
    """
    Reverse-engineers the hardware wires back into human-readable Assembly.
    """
    # 1. Reverse ABI Mapping for readable registers
    ABI_NAMES = [
        'zero', 'ra', 'sp', 'gp', 'tp', 't0', 't1', 't2',
        's0', 's1', 'a0', 'a1', 'a2', 'a3', 'a4', 'a5',
        'a6', 'a7', 's2', 's3', 's4', 's5', 's6', 's7',
        's8', 's9', 's10', 's11', 't3', 't4', 't5', 't6'
    ]

    def reg(idx):
        return f"x{idx}({ABI_NAMES[idx]})" if 0 <= idx < 32 else f"x{idx}"

    # Sign-extend the 12-bit immediate for display purposes
    # (If the 12th bit is 1, it's negative)
    imm_dec = imm_o if imm_o < 0x800 else imm_o - 0x1000

    # --- I-TYPE: ADDI (Opcode 19) ---
    if op_o == 19:
        return f"addi {reg(rd_o)}, {reg(rs1_o)}, {imm_dec}"

    # --- U-TYPE: LUI (Opcode 55) ---
    elif op_o == 55:
        # LUI immediate is 20 bits; display it beautifully in hex
        return f"lui  {reg(rd_o)}, 0x{imm_o:05x}"

    # --- R-TYPE: ALL ALU OPERATIONS (Opcode 51) ---
    elif op_o == 51:
        # The Hardware Reverse-Lookup Table
        rtype_reverse_map = {
            (0, 0x00): "add",
            (0, 0x20): "sub",
            (1, 0x00): "sll",
            (2, 0x00): "slt",
            (3, 0x00): "sltu",
            (4, 0x00): "xor",
            (5, 0x00): "srl",
            (5, 0x20): "sra",
            (6, 0x00): "or",
            (7, 0x00): "and"
        }

        # Look up the mnemonic based on the f3 and f7 wires
        mnemonic = rtype_reverse_map.get((f3_o, f7_o), "unknown_R")
        return f"{mnemonic:<4} {reg(rd_o)}, {reg(rs1_o)}, {reg(rs2_o)}"

    # --- I-TYPE: LOADS (Opcode 3) ---
    elif op_o == 3:
        mnemonic = "lb" if f3_o == 0 else "lw" if f3_o == 2 else "unknown_L"
        return f"{mnemonic:<4} {reg(rd_o)}, {imm_dec}({reg(rs1_o)})"

    # --- S-TYPE: STORES (Opcode 35) ---
    elif op_o == 35:
        mnemonic = "sb" if f3_o == 0 else "sw" if f3_o == 2 else "unknown_S"
        return f"{mnemonic:<4} {reg(rs2_o)}, {imm_dec}({reg(rs1_o)})"

    # --- I-TYPE: LOADS (Opcode 3) ---
    elif op_o == 3:
        load_rev_map = {0: "lb", 1: "lh", 2: "lw", 4: "lbu", 5: "lhu"}
        mnemonic = load_rev_map.get(f3_o, "unknown_L")
        return f"{mnemonic:<4} {reg(rd_o)}, {imm_dec}({reg(rs1_o)})"

    # --- S-TYPE: STORES (Opcode 35) ---
    elif op_o == 35:
        store_rev_map = {0: "sb", 1: "sh", 2: "sw"}
        mnemonic = store_rev_map.get(f3_o, "unknown_S")
        return f"{mnemonic:<4} {reg(rs2_o)}, {imm_dec}({reg(rs1_o)})"
    # --- U-TYPE: AUIPC (Opcode 23) ---
    elif op_o == 23:
        return f"auipc {reg(rd_o)}, 0x{imm_o:05x}"

    # --- I-TYPE: JALR (Opcode 103) ---
    elif op_o == 103:
        # 12-bit Sign Extension
        imm_dec = imm_o if imm_o < 0x800 else imm_o - 0x1000
        return f"jalr {reg(rd_o)}, {imm_dec}({reg(rs1_o)})"

    # --- J-TYPE: JAL (Opcode 111) ---
    elif op_o == 111:
        # 21-bit Sign Extension for jump target accuracy
        imm_dec = imm_o if imm_o < 0x100000 else imm_o - 0x200000
        return f"jal  {reg(rd_o)}, {imm_dec}"

    # --- B-TYPE: BRANCHES (Opcode 99) ---
    elif op_o == 99:
        # 13-bit Sign Extension for branch target accuracy
        imm_dec = imm_o if imm_o < 0x1000 else imm_o - 0x2000

        branch_rev_map = {0: "beq", 1: "bne", 4: "blt", 5: "bge", 6: "bltu", 7: "bgeu"}
        mnemonic = branch_rev_map.get(f3_o, "unknown_B")
        return f"{mnemonic:<4} {reg(rs1_o)}, {reg(rs2_o)}, {imm_dec}"


    return f"UNKNOWN OPCODE: {op_o}"

"""Helper Function & Utilities"""

# ==========================================
# CELL 1: HELPER FUNCTIONS
# ==========================================
def generate_hex_file(asm_filename, hex_filename):
    """
    Converts assembly source code into a hexadecimal machine code file.
    Returns the total number of instructions assembled.
    """
    total_instr = 0
    try:
        with open(asm_filename, 'r') as asm_in, open(hex_filename, 'w') as hex_out:
            for line in asm_in:
                # Remove comments and whitespace to avoid assembly errors
                clean_line = line.split('#')[0].strip()
                if not clean_line:
                    continue

                machine_code = mini_assembler(clean_line)

                if machine_code is not None and machine_code != 0:
                    # Write as an 8-character hex string (32 bits)
                    hex_string = f"{machine_code & 0xFFFFFFFF:08x}\n"
                    hex_out.write(hex_string)
                    total_instr += 1

        print(f"✅ Success: {hex_filename} generated ({total_instr} instructions).")
        return total_instr

    except FileNotFoundError:
        print(f"❌ Error: {asm_filename} not found.")
        return 0


def to_signed_32(val_i):
    """
    Evaluates a 32-bit hardware wire as a signed integer.
    Enforces the negative minimum bound for Two's Complement math.
    """
    # Enforce maximum 32-bit wire limit
    val = val_i & 0xFFFFFFFF
    # Check if the 31st bit (Sign) is 1
    if val & 0x80000000:
        return val - 0x100000000 # Map to negative minimum bound
    return val

"""Hardware State (Memory & Registers)"""

# ==========================================
# CELL 2: HARDWARE STATE (Storage Elements)
# ==========================================
class PCState:
    """Physical storage for the Program Counter Flip-Flop"""
    def __init__(self):
        self.current_pc = 0x00000000

    def update(self, val):
        # Hardware Constraint: PC must be between minimum (0x0) and maximum (0xFFFFFFFF)
        if val < 0x00000000 or val > 0xFFFFFFFF:
            raise ValueError(f"HARDWARE FAULT: PC Address Out of Bounds (0x{val:08x})")
        self.current_pc = val

    def read(self):
        return self.current_pc

class RegisterFile:
    def __init__(self):
        # Initialize 32 registers to 0
        self.registers = [0] * 32

    def read_rs1(self, addr):
        """Port RD1: Combinational Read"""
        return 0 if addr == 0 else self.registers[addr] & 0xFFFFFFFF

    def read_rs2(self, addr):
        """Port RD2: Combinational Read"""
        return 0 if addr == 0 else self.registers[addr] & 0xFFFFFFFF

    def write(self, addr, data, we):
        """Port WD: Sequential Write with x0 Protection"""
        # Hardware 'Safety Gate': x0 cannot be overwritten
        if we and addr != 0:
            self.registers[addr] = data & 0xFFFFFFFF

class DataMemory:
    """
    Simulated SRAM Macro with 4-bit Write Strobe Support.
    Uses a sparse dictionary for infinite, memory-safe addressing.
    """
    def __init__(self):
        # Keys are 32-bit aligned addresses, Values are 32-bit words
        self.memory = {}

    def read(self, address_i):
        # Hardware enforces word-alignment by ignoring the bottom 2 bits
        base_addr = address_i & 0xFFFFFFFC
        return self.memory.get(base_addr, 0)

    def write(self, address_i, write_data_i, we_i):
        if we_i == 0:
            return

        base_addr = address_i & 0xFFFFFFFC

        # Read the current word from memory (or 0 if it's empty)
        current_word = self.memory.get(base_addr, 0)
        new_word = current_word

        # --- THE HARDWARE BYTE MASKS ---
        # Only overwrite the specific bytes authorized by the 4-bit strobe (we_i)

        # Byte 0 (Bits 7:0)
        if (we_i & 0b0001):
            new_word = (new_word & 0xFFFFFF00) | (write_data_i & 0x000000FF)

        # Byte 1 (Bits 15:8)
        if (we_i & 0b0010):
            new_word = (new_word & 0xFFFF00FF) | (write_data_i & 0x0000FF00)

        # Byte 2 (Bits 23:16)
        if (we_i & 0b0100):
            new_word = (new_word & 0xFF00FFFF) | (write_data_i & 0x00FF0000)

        # Byte 3 (Bits 31:24)
        if (we_i & 0b1000):
            new_word = (new_word & 0x00FFFFFF) | (write_data_i & 0xFF000000)

        # Commit the surgically modified word back to memory
        self.memory[base_addr] = new_word

# ==========================================
# CELL 2 UPDATE: Add Hex File Loading
# ==========================================

class InstructionMemory:
    def __init__(self):
        self.memory = {}

    def load_instruction(self, address_i, instruction_i):
        addr = address_i & 0xFFFFFFFF
        self.memory[addr] = instruction_i & 0xFFFFFFFF

    def load_from_hex_file(self, filename_i):
        """Mimics the SystemVerilog $readmemh system task."""
        addr = 0x00000000
        with open(filename_i, 'r') as f:
            for line in f:
                clean_line = line.strip()
                if clean_line:
                    # Parse the hex string and enforce 32-bit maximum hardware boundary
                    instruction = int(clean_line, 16) & 0xFFFFFFFF
                    self.memory[addr] = instruction
                    # Advance to the next 32-bit word address
                    addr += 4

    def read(self, pc_i):
        addr = pc_i & 0xFFFFFFFF
        return self.memory.get(addr, 0)

"""Decoder, Immediate generator, branch control unit, load & store alignment units"""

def module_pc_plus_4(pc_curr):
    """
    Standalone PC+4 Adder.
    In Hardware: A dedicated 32-bit incrementer.
    """
    return (pc_curr + 4) & 0xFFFFFFFF

"""IMM GENERATOR, SAU, LAU"""

# ==========================================
# LOAD ALIGNMENT UNIT (LAU)
# ==========================================

def module_lau(raw_mem_data_i, adrs_1_i, adrs_0_i, funct3_i):
    """
    Extracts bytes/halfwords from a 32-bit memory word and enforces sign-extensions.
    """
    # Combine the bottom two address wires to find the byte offset (0, 1, 2, or 3)
    byte_offset = (adrs_1_i << 1) | adrs_0_i

    # Shift the raw 32-bit memory word so our target data is at the very bottom
    shifted_data = (raw_mem_data_i >> (byte_offset * 8)) & 0xFFFFFFFF

    if funct3_i == 0x0: # LB (Load Byte - Signed)
        val = shifted_data & 0xFF # Enforce 8-bit maximum hardware limit
        if val & 0x80:            # Check the 8th wire (sign bit)
            return val | 0xFFFFFF00
        return val

    elif funct3_i == 0x1: # LH (Load Halfword - Signed)
        val = shifted_data & 0xFFFF # Enforce 16-bit maximum hardware limit
        if val & 0x8000:            # Check the 16th wire (sign bit)
            return val | 0xFFFF0000
        return val

    elif funct3_i == 0x2: # LW (Load Word)
        return shifted_data & 0xFFFFFFFF # Enforce absolute 32-bit limit

    elif funct3_i == 0x4: # LBU (Load Byte - Unsigned)
        return shifted_data & 0xFF # Zero-extend by naturally masking

    elif funct3_i == 0x5: # LHU (Load Halfword - Unsigned)
        return shifted_data & 0xFFFF # Zero-extend by naturally masking

    return 0

# ==========================================
# STORE ALIGNMENT UNIT (SAU)
# ==========================================

def module_sau(rd2_data_i, adrs_1_i, adrs_0_i, funct3_i):
    byte_offset = (adrs_1_i << 1) | adrs_0_i
    
    # Just shift the raw data, let the byte_mask_o handle the protection
    aligned_data_o = (rd2_data_i << (byte_offset * 8)) & 0xFFFFFFFF
    byte_mask_o = 0

    if funct3_i == 0x0:   # SB
        byte_mask_o = (0x1 << byte_offset) & 0xF
    elif funct3_i == 0x1: # SH
        byte_mask_o = (0x3 << byte_offset) & 0xF
    elif funct3_i == 0x2: # SW
        byte_mask_o = 0xF

    return aligned_data_o, byte_mask_o


"""ALU"""
def module_alu(src1_i, src2_i, alu_op_i, DEBUG_MODE=False):
    """
    Arithmetic Logic Unit (ALU) - Full RV32I Base Integer Support
    """
    # Map the incoming integer from the Controller/Cocotb to the internal string logic
    ALU_OPS = {
        0: "ADD", 1: "SUB", 2: "SLL", 3: "SLT", 
        4: "SLTU", 5: "XOR", 6: "SRL", 7: "SRA", 
        8: "OR", 9: "AND"
    }
    
    # Safely grab the string, default to pass-through if invalid
    op_string = ALU_OPS.get(alu_op_i, "PASS")

    # 1. Unsigned 32-bit wire boundaries
    a_i = src1_i & 0xFFFFFFFF
    b_i = src2_i & 0xFFFFFFFF

    # 2. Signed conversion for hardware flag checks and Arithmetic Shifts
    a_s = a_i if a_i < 0x80000000 else a_i - 0x100000000
    b_s = b_i if b_i < 0x80000000 else b_i - 0x100000000

    res_o = 0
    carry_o = 0
    ovfl_o = 0

    # 3. The ALU Core Execution (The Big Multiplexer)
    if op_string == "ADD":
        res_o = a_i + b_i
        carry_o = 1 if res_o > 0xFFFFFFFF else 0

        # Mask to 32 bits, then convert to signed to check hardware wrap-around
        res_signed = res_o & 0xFFFFFFFF
        res_signed = res_signed if res_signed < 0x80000000 else res_signed - 0x100000000
        # Evaluate overflow against the physically truncated result
        ovfl_o = 1 if (a_s > 0 and b_s > 0 and res_signed < 0) or \
                      (a_s < 0 and b_s < 0 and res_signed >= 0) else 0
    elif op_string == "SUB":
        res_o = a_i - b_i
        carry_o = 1 if a_i >= b_i else 0 # Unsigned borrow
        # Mask to 32 bits, then convert to signed to check hardware wrap-around
        res_signed = res_o & 0xFFFFFFFF
        res_signed = res_signed if res_signed < 0x80000000 else res_signed - 0x100000000
        # Evaluate overflow against the physically truncated result
        ovfl_o = 1 if (a_s >= 0 and b_s < 0 and res_signed < 0) or \
                      (a_s < 0 and b_s > 0 and res_signed >= 0) else 0

    # Bitwise Operations
    elif op_string == "AND":
        res_o = a_i & b_i
    elif op_string == "OR":
        res_o = a_i | b_i
    elif op_string == "XOR":
        res_o = a_i ^ b_i

    # Shift Operations (RISC-V only looks at the bottom 5 bits of the shift amount)
    elif op_string == "SLL":  # Shift Left Logical
        shift_amt = b_i & 0x1F
        res_o = a_i << shift_amt

    elif op_string == "SRL":  # Shift Right Logical (Fills with 0s)
        shift_amt = b_i & 0x1F
        res_o = a_i >> shift_amt

    elif op_string == "SRA":  # Shift Right Arithmetic (Preserves Sign Bit)
        shift_amt = b_i & 0x1F
        # We use the signed version (a_s) here because Python natively
        # sign-extends negative integers when using >>
        res_o = a_s >> shift_amt

    # Comparison Operations
    elif op_string == "SLT":  # Set Less Than (Signed)
        res_o = 1 if a_s < b_s else 0

    elif op_string == "SLTU": # Set Less Than Unsigned
        res_o = 1 if a_i < b_i else 0

    else:
        # Pass-through or unhandled opcode fallback
        res_o = b_i

    # 4. Final output wire masking and Zero/Sign flag generation
    final_res_o = res_o & 0xFFFFFFFF
    z_o = 1 if final_res_o == 0 else 0
    s_o = (final_res_o >> 31) & 1

    # 5. Logic Analyzer Trace (Controlled by DEBUG_MODE flag)
    if DEBUG_MODE:
        flag_str = f"Z:{z_o} S:{s_o} V:{ovfl_o} C:{carry_o}"
        print("\n--- Inside ALU-------")
        print(f"ALU-CORE | A: 0x{a_i:08x} | B: 0x{b_i:08x} | OP: {op_string:<4} (Int: {alu_op_i})")
        print(f"ALU-OUT  | RES: 0x{final_res_o:08x} | FLAGS: [{flag_str}]\n")

    return final_res_o, z_o, s_o, ovfl_o, carry_o

"""CTRL"""
def module_ctrl(opcode_i, funct3_i, funct7_i, DEBUG_MODE=False):
    """
    Audited RV32I Control Unit.
    Logic mapped to 'Chip Design with Rashid' Microarchitecture.
    Now outputting integer ENUMs for alu_ctrl_o.
    """
    op = opcode_i & 0x7F

    # --- Hardware Defaults (Reset State) ---
    is_cond_branch_o, is_jal_o, is_jalr_o = 0, 0, 0
    imm_src_o, alu_src1_ctrl_o, alu_src2_ctrl_o = 0, 1, 0
    
    # 0 maps to "ADD"
    alu_ctrl_o = 0 
    
    datamem_re_o, datamem_we_o, dataMem2Reg_o, regfile_we_o = 0, 0, 0, 0

    # --- Instruction Decoding Logic ---

    if op == 51:    # 0x33: R-TYPE (Reg-Reg)
        regfile_we_o = 1
        if funct3_i == 0 and funct7_i == 32: alu_ctrl_o = 1  # sub
        elif funct3_i == 0: alu_ctrl_o = 0                   # add
        elif funct3_i == 1: alu_ctrl_o = 2                   # sll
        elif funct3_i == 2: alu_ctrl_o = 3                   # slt
        elif funct3_i == 3: alu_ctrl_o = 4                   # sltu
        elif funct3_i == 4: alu_ctrl_o = 5                   # xor
        elif funct3_i == 5 and funct7_i == 32: alu_ctrl_o = 7 # sra
        elif funct3_i == 5: alu_ctrl_o = 6                   # srl
        elif funct3_i == 6: alu_ctrl_o = 8                   # or
        elif funct3_i == 7: alu_ctrl_o = 9                   # and

    elif op == 19:  # 0x13: I-TYPE (Reg-Imm)
        regfile_we_o, alu_src2_ctrl_o = 1, 1
        if funct3_i == 0: alu_ctrl_o = 0                     # addi
        elif funct3_i == 2: alu_ctrl_o = 3                   # slti
        elif funct3_i == 3: alu_ctrl_o = 4                   # sltiu
        elif funct3_i == 4: alu_ctrl_o = 5                   # xori
        elif funct3_i == 6: alu_ctrl_o = 8                   # ori
        elif funct3_i == 7: alu_ctrl_o = 9                   # andi
        elif funct3_i == 1: alu_ctrl_o = 2                   # slli
        elif funct3_i == 5:
            if funct7_i == 32: alu_ctrl_o = 7                # srai
            else: alu_ctrl_o = 6                             # srli

    elif op == 3:   # 0x03: LOAD
        regfile_we_o, alu_src2_ctrl_o, datamem_re_o, dataMem2Reg_o = 1, 1, 1, 1

    elif op == 35:  # 0x23: STORE
        imm_src_o, alu_src2_ctrl_o, datamem_we_o = 1, 1, 1

    elif op == 99:  # 0x63: BRANCH
        is_cond_branch_o, imm_src_o, alu_ctrl_o = 1, 2, 1    # 1 maps to "SUB"

    elif op == 55:  # 0x37: LUI (Load Upper Imm)
        # src1=2 (Zero), src2=1 (Imm), imm_src=3 (U-type)
        regfile_we_o, imm_src_o, alu_src1_ctrl_o, alu_src2_ctrl_o = 1, 3, 2, 1

    elif op == 23:  # 0x17: AUIPC (Add Upper Imm to PC)
        # src1=0 (PC), src2=1 (Imm), imm_src=3 (U-type)
        regfile_we_o, imm_src_o, alu_src1_ctrl_o, alu_src2_ctrl_o = 1, 3, 0, 1

    elif op == 103: # 0x67: JALR
        # 0 maps to "ADD"
        is_jalr_o, regfile_we_o, alu_src1_ctrl_o, alu_src2_ctrl_o, alu_ctrl_o, dataMem2Reg_o = 1, 1, 1, 1, 0, 2

    elif opcode_i == 111: # 0x6F: JAL
        is_jal_o, regfile_we_o, imm_src_o, dataMem2Reg_o, datamem_re_o, datamem_we_o = 1, 1, 4, 2, 0, 0

    # --- Print Trace ---
    if DEBUG_MODE:
        # Reverse mapping just for a human-readable printout
        REVERSE_ALU_OPS = {
            0: "ADD", 1: "SUB", 2: "SLL", 3: "SLT", 
            4: "SLTU", 5: "XOR", 6: "SRL", 7: "SRA", 
            8: "OR", 9: "AND"
        }
        alu_str = REVERSE_ALU_OPS.get(alu_ctrl_o, "UNKNOWN")

        print(f"\n--- inside the module module_ctrl ---")
        print(f"INPUTS  | op_i: {opcode_i} | f3_i: {funct3_i} | f7_i: {funct7_i}\n"
              f"OUTPUTS | Mem: [RE:{datamem_re_o}, WE:{datamem_we_o}]\n"
              f"        | BCU [IS-COND-BRANCH:{is_cond_branch_o}, IS_JAL:{is_jal_o}, IS_JALR:{is_jalr_o}]\n"
              f"        | Data: [ImmSrc:{imm_src_o}, S1:{alu_src1_ctrl_o}, S2:{alu_src2_ctrl_o}, ALU:{alu_str} ({alu_ctrl_o}), D2R:{dataMem2Reg_o}, RFWE:{regfile_we_o}]")

    return (is_cond_branch_o, is_jal_o, is_jalr_o, imm_src_o,
            alu_src1_ctrl_o, alu_src2_ctrl_o, alu_ctrl_o,
            datamem_re_o, datamem_we_o, dataMem2Reg_o, regfile_we_o)
""" RF """
def module_register_file(rs1_addr_i, rs2_addr_i, rd_addr_i, rd_data_i, rf_we_i, reg_file_obj):
    """
    Register File (Mapped to Physical RegFile Object)
    Handles 2 Reads and 1 Write per cycle.
    """


    # 1. READ PORT 1 & 2
    # Logic: rs1_addr_i and rs2_addr_i are 5-bit pointers (0-31)
    rs1_val_o = reg_file_obj.read_rs1(rs1_addr_i)
    rs2_val_o = reg_file_obj.read_rs2(rs2_addr_i)

    # 2. WRITE PORT (Only on Clock Edge if WE is high)
    # Hardware Note: x0 is hardwired to 0. Logic inside the object handles this,
    # but we can print a check here.
    if rf_we_i and rd_addr_i != 0:
        reg_file_obj.write(rd_addr_i, rd_data_i, rf_we)
        print(f"ACTION  | Writing 0x{rd_data_i:08x} to x{rd_addr_i}")
    elif rf_we_i and rd_addr_i == 0:
        print(f"ACTION  | Attempted write to x0 ignored (Hardwired to 0)")

    print ("\n**** Inside RF ******")
    print(f"INPUTS  | rs1_addr: {rs1_addr_i} | rs2_addr: {rs2_addr_i} | rd_addr: {rd_addr_i}\n"
          f"        | rf_we: {rf_we_i} | rd_data: 0x{rd_data_i:08x}\n"
          f"OUTPUTS | rs1_val: 0x{rs1_val_o:08x} | rs2_val: 0x{rs2_val_o:08x}")

    return rs1_val_o, rs2_val_o

def module_alu_in_muxes(pc_curr_i, rs1_val_i, rs2_val_i, imm_i, s1_sel_i, s2_sel_i):
    """
    ALU Input Multiplexers (The Orange Box)
    s1_sel_i: 0=RS1, 1=PC
    s2_sel_i: 0=RS2, 1=IMM
    """
    # --- Mux A: 3-to-1 Selection ---
    if s1_sel_i == 0:
        alu_a_o = pc_curr_i      # Path from Register File RD1
    elif s1_sel_i == 1:
        alu_a_o = rs1_val_i       # Path from Program Counter
    else:
        alu_a_o = 0               # Hardwired Zero path

    # --- Mux B: 2-to-1 Selection ---
    if s2_sel_i == 0:
        alu_b_o = rs2_val_i      # Path from Register File RD1
    elif s2_sel_i == 1:
        alu_b_o = imm_i       # Path from Program Counter


    print ("\n**** Inside alu_input_muxes ******")
    # Logic Analyzer Trace
    print(f"INPUTS  | pc: 0x{pc_curr_i:08x} | rs1: 0x{rs1_val_i:08x} | s1_sel: {s1_sel_i}\n"
          f"        | imm: 0x{imm_i:08x} | rs2: 0x{rs2_val_i:08x} | s2_sel: {s2_sel_i}\n"
          f"OUTPUTS | alu_a_o: 0x{alu_a_o:08x} | alu_b_o: 0x{alu_b_o:08x}")

    return alu_a_o, alu_b_o

def module_rf_wb_mux(alu_res_i, lau_res_i, pc_plus_4_i, d2r_sel_i):
    """
    RF Write-Back Mux (The Yellow Box)
    d2r_sel_i: 0=ALU, 1=LAU (Memory), 2=PC+4
    """
    print(f"--- inside the module module_rf_wb_mux ---")

    # Selection Logic based on the Control Unit 'D2R' signal
    if d2r_sel_i == 0:
        rf_wd_o = alu_res_i       # Path from ALU (Pink wire)
    elif d2r_sel_i == 1:
        rf_wd_o = lau_res_i       # Path from LAU (Brown wire)
    elif d2r_sel_i == 2:
        rf_wd_o = pc_plus_4_i     # Path from pc_plus_4 (Green wire)
    else:
        rf_wd_o = 0               # Safety/Default

    # Logic Analyzer Trace for Debugging
    print ("\n**** Inside rf_wb_mux ******")
    print(f"INPUTS  | alu_res: 0x{alu_res_i:08x} | lau_res: 0x{lau_res_i:08x}\n"
          f"        | pc+4:    0x{pc_plus_4_i:08x} | d2r_sel: {d2r_sel_i}\n"
          f"OUTPUTS | rf_wd_o:  0x{rf_wd_o:08x}")

    return rf_wd_o


def module_decoder(instr_i):
    """
    The 'Wire Stripper': Extracts physical fields from the 32-bit instruction.
    Matches the purple 'DECODER' block in your schematic.
    """
    # 1. Opcode [6:0] - Determines the instruction type
    op_o = instr_i & 0x7F

    # 2. Destination Register [11:7] - rd
    rd_o = (instr_i >> 7) & 0x1F

    # 3. func3 [14:12] - Minor opcode/ALU selection
    f3_o = (instr_i >> 12) & 0x7

    # 4. Source Register 1 [19:15] - rs1
    rs1_o = (instr_i >> 15) & 0x1F

    # 5. Source Register 2 [24:20] - rs2
    rs2_o = (instr_i >> 20) & 0x1F

    # 6. func7 [31:25] - Additional ALU/Instruction selection
    f7_o = (instr_i >> 25) & 0x7F

    # 7. IMMEDIATE GENERATION (Internal to the Decoder Block)
    imm_o = 0

    # R-type: (No immediate)
    if op_o == 0x33:
        imm_o = 0

    # I-type: (addi, lw, jalr) -> 12-bit signed
    elif op_o in [0x13, 0x03, 0x67]:
        imm_11_0 = (instr_i >> 20) & 0xFFF
        imm_o = imm_11_0 if imm_11_0 < 0x800 else imm_11_0 - 0x1000

    # S-type: (sw, sb, sh)
    elif op_o == 0x23:
        imm_11_5 = (instr_i >> 25) & 0x7F
        imm_4_0   = (instr_i >> 7) & 0x1F
        imm_12b   = (imm_11_5 << 5) | imm_4_0
        imm_o = imm_12b if imm_12b < 0x800 else imm_12b - 0x1000

    # B-type: (beq, bne...)
    elif op_o == 0x63:
        b12 = (instr_i >> 31) & 0x1
        b11 = (instr_i >> 7) & 0x1
        b10_5 = (instr_i >> 25) & 0x3F
        b4_1 = (instr_i >> 8) & 0xF
        imm_13b = (b12 << 12) | (b11 << 11) | (b10_5 << 5) | (b4_1 << 1)
        imm_o = imm_13b if imm_13b < 0x1000 else imm_13b - 0x2000

    # U-type: (lui, auipc)
    elif op_o in [0x37, 0x17]:
        imm_o = instr_i & 0xFFFFF000

    # J-type: (jal)
    elif op_o == 0x6F:
        j20 = (instr_i >> 31) & 0x1
        j19_12 = (instr_i >> 12) & 0xFF
        j11 = (instr_i >> 20) & 0x1
        j10_1 = (instr_i >> 21) & 0x3FF
        imm_21b = (j20 << 20) | (j19_12 << 12) | (j11 << 11) | (j10_1 << 1)
        imm_o = imm_21b if imm_21b < 0x100000 else imm_21b - 0x200000

    print(f"\n--- inside the module module_decoder ---")
    print(f"OUTPUTS | op: {op_o} | rd: {rd_o} | rs1: {rs1_o} | rs2: {rs2_o}\n"
          f"        | f3: {f3_o} | f7: {f7_o} | imm: 0x{imm_o & 0xFFFFFFFF:08x} ({imm_o})")

    return op_o, rd_o, rs1_o, rs2_o, f3_o, f7_o, imm_o

"""NEXT PC Logic"""

def module_next_pc_logic(pc_curr_i, pc_plus_4_i, imm_i, alu_res_i, pc_src_i):
    """
    Next-PC Logic (Sequencer Multiplexer)
    """
    # Internal Hardware: Branch Target Adder
    branch_target_o = (pc_curr_i + imm_i) & 0xFFFFFFFF

    # Internal Hardware: JALR LSB Masking
    jalr_target_o = alu_res_i & 0xFFFFFFFE

    # 3:1 Mux Selection logic
    if pc_src_i == 2:
        pc_next_o = jalr_target_o
    elif pc_src_i == 1:
        pc_next_o = branch_target_o
    else:
        pc_next_o = pc_plus_4_i
    # Grouping inputs and the final hardware 'wire' result
    print("\n---- inside next_pc_logic module-----")
    print(f"INPUTS  | pc_curr: 0x{pc_curr_i:08x} | imm: 0x{imm_i & 0xFFFFFFFF:08x} | pc_src: {pc_src_i}\n"
          f"        | pc+4: 0x{pc_plus_4_i:08x} | alu_res: 0x{alu_res_i & 0xFFFFFFFF:08x}\n"
          f"INTERNAL| pc+imm: 0x{branch_target_o:08x} | alu_res_i/jalr_target_o: 0x{jalr_target_o:08x}\n"
          f"OUTPUTS | pc_next_o:  0x{pc_next_o:08x}")

    return pc_next_o

"""BCU"""

def module_bcu(f3_i, flags_i, is_cond_branch_i, is_jal_i, is_jalr_i):
    """
    Branch Control Unit (Master Sequencer)
    Returns: pc_src_o (0=PC+4, 1=Target_Imm, 2=ALU_Res)
    """
    print(f"--- inside the module module_bcu ---")

    # Unpack flags for the print and logic
    z_i, s_i, o_i, c_i = flags_i

    # 1. Evaluate Conditional Branch Logic
    take_branch_o = False
    if is_cond_branch_i:
        if   f3_i == 0: take_branch_o = (z_i == 1)      # BEQ
        elif f3_i == 1: take_branch_o = (z_i == 0)      # BNE
        elif f3_i == 4: take_branch_o = (s_i != o_i)    # BLT
        elif f3_i == 5: take_branch_o = (s_i == o_i)    # BGE
        elif f3_i == 6: # BLTU (Branch < Unsigned)
            # Take branch if there was a Borrow (C=0)
            # FIX: Use 'take_branch_o' and 'c_i'
            take_branch_o = (c_i == 0)

        elif f3_i == 7: # BGEU (Branch >= Unsigned)
            # Take branch if there was No Borrow (C=1)
            # FIX: Use 'take_branch_o' and 'c_i'
            take_branch_o = (c_i == 1)

    # 2. Priority Encoder Logic
    if is_jalr_i:
        pc_src_o = 2
    elif is_jal_i or take_branch_o:
        pc_src_o = 1
    else:
        pc_src_o = 0

    # Grouping Inputs and Outputs for the Trace
    print("\n ---- Inside module BCU -------")
    print(f"INPUTS  | f3: {f3_i} | Flags: [Z:{z_i}, S:{s_i}, O:{o_i}, C:{c_i}]\n"
          f"        | Ctrl: [BR:{is_cond_branch_i}, JAL:{is_jal_i}, JALR:{is_jalr_i}]\n"
          f"OUTPUTS | take_branch: {take_branch_o} | pc_src_o: {pc_src_o}")

    return pc_src_o

"""instruction memory"""

def module_instruction_memory(addr_i, mem_inst):
    """
    Instruction Memory Module (The Green Box)
    addr_i: 32-bit address from the PC
    mem_inst: The actual InstructionMemory storage object
    """
    # In SystemVerilog, this would be:
    # assign instr_o = mem_array[addr_i >> 2];

    # 1. Hardware Boundary Check (Alignment)
    # Real instructions must be 4-byte aligned
    if addr_i % 4 != 0:
        print(f"⚠️  HARDWARE ALIGNMENT FAULT: PC 0x{addr_i:08x} is not 4-byte aligned!")

    # 2. Fetch the instruction
    instr_o = mem_inst.read(addr_i)

    # 3. Logic Analyzer Trace
    # print(f"FETCH-UNIT | ADDR: 0x{addr_i:08x} | DATA: 0x{instr_o:08x}")

    return instr_o

"""Data Memory"""

def module_data_memory(addr_i, wdata_i, we_mask_i, re_i, we_i, mem_inst):
    """
    SRAM Macro Interface (Memory Tier)
    we_mask_i: 4-bit write strobe from the SAU
    """
    print("\n--- inside module data_memory -----")
    if we_i:
        # The 'we_mask_i' ensures we don't accidentally corrupt
        # the other 24 bits when doing a 'sb' (Store Byte).
        mem_inst.write(addr_i, wdata_i, we_mask_i)

        # Logic Analyzer Debug
        print(f"  [SRAM-WRITE] ADDR: 0x{addr_i:08x} | DATA: 0x{wdata_i:08x} | STROBE: {we_mask_i:04b}")
        return 0

    if re_i:
        # 1. Fetch the raw 32-bit word from physical memory
        read_data_o = mem_inst.read(addr_i)

        # 2. Logic Analyzer Debug
        print(f"  [SRAM-READ]  ADDR: 0x{addr_i:08x} | DATA: 0x{read_data_o:08x} | (Raw 32-bit output)")

        # 3. Send it down the wire to the LAU
        return read_data_o

    return 0

"""PC"""

def module_pc_reg(pc_next_i, en_pc_i, reset_i, pc_inst):
    """
    PC Register Sub-System (The Instruction Pointer)
    reset_i: 1 = Force PC to 0x0 (Priority over enable)
    en_pc_i: 1 = Update PC with next address, 0 = Stall
    """
    if reset_i:
        pc_inst.update(0x00000000)
    elif en_pc_i:
        pc_inst.update(pc_next_i)

    return pc_inst.read()

